//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicDiary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int Subjects_Id { get; set; }
        public int Groups_Id { get; set; }
        public int LessonNumber { get; set; }
        public string WeekDay { get; set; }
        public int Teachers_Id { get; set; }
        public string Description { get; set; }
    }
}
